// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlilJSdQYwIp_O-pQsc2PYZrJyDkwRiQo',
    appId: '1:279028940501:web:1b9e47ee62360b1d096c5c',
    messagingSenderId: '279028940501',
    projectId: 'scrapconnect-32544',
    authDomain: 'scrapconnect-32544.firebaseapp.com',
    storageBucket: 'scrapconnect-32544.appspot.com',
    measurementId: 'G-SN96ECQF6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRheraX8qeSoEUtwmpUJDdeaAQ2_bJc34',
    appId: '1:279028940501:android:f9602d4c95ed448a096c5c',
    messagingSenderId: '279028940501',
    projectId: 'scrapconnect-32544',
    storageBucket: 'scrapconnect-32544.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAap6mJnNu5n1EWtk6tIOv-eDfPgVSvZ0g',
    appId: '1:279028940501:ios:dafba94abf9c64f2096c5c',
    messagingSenderId: '279028940501',
    projectId: 'scrapconnect-32544',
    storageBucket: 'scrapconnect-32544.appspot.com',
    iosBundleId: 'com.example.scrapConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAap6mJnNu5n1EWtk6tIOv-eDfPgVSvZ0g',
    appId: '1:279028940501:ios:b9c94bd4cb8c2ccf096c5c',
    messagingSenderId: '279028940501',
    projectId: 'scrapconnect-32544',
    storageBucket: 'scrapconnect-32544.appspot.com',
    iosBundleId: 'com.example.scrapConnect.RunnerTests',
  );
}
