// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG3p93bfevcuDuXxsT7iALoYVhVwgkidA',
    appId: '1:171393660081:web:5ceeb7ef0b33335ecade90',
    messagingSenderId: '171393660081',
    projectId: 'scrapconnect-dba28',
    authDomain: 'scrapconnect-dba28.firebaseapp.com',
    storageBucket: 'scrapconnect-dba28.appspot.com',
    measurementId: 'G-RV58D3C85P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApX-xtIeT_QwdvGUI2taqizJYEu5_8ibc',
    appId: '1:171393660081:android:c0781c5fa7f110b0cade90',
    messagingSenderId: '171393660081',
    projectId: 'scrapconnect-dba28',
    storageBucket: 'scrapconnect-dba28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrCYSQbZBfc6qgkwCy3bPibXYdA-Ynksw',
    appId: '1:171393660081:ios:c56fd47bb4fef5facade90',
    messagingSenderId: '171393660081',
    projectId: 'scrapconnect-dba28',
    storageBucket: 'scrapconnect-dba28.appspot.com',
    iosBundleId: 'com.example.scrapConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrCYSQbZBfc6qgkwCy3bPibXYdA-Ynksw',
    appId: '1:171393660081:ios:367ef1b5f0009401cade90',
    messagingSenderId: '171393660081',
    projectId: 'scrapconnect-dba28',
    storageBucket: 'scrapconnect-dba28.appspot.com',
    iosBundleId: 'com.example.scrapConnect.RunnerTests',
  );
}
