import 'package:flutter/material.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key, required this.username}) : super(key: key);

  final String username;

  @override
  _HomeScreenState createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  int _currentIndex = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Welcome, ${widget.username}!'),
      ),
      body: IndexedStack(
        index: _currentIndex,
        children: [
          RateListPage(),
          DealersListPage(),
        ],
      ),
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: _currentIndex,
        onTap: (index) {
          setState(() {
            _currentIndex = index;
          });
        },
        items: [
          BottomNavigationBarItem(
            icon: Icon(Icons.list),
            label: 'Rate List',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.people),
            label: 'Dealers List',
          ),
        ],
      ),
    );
  }
}

class RateListPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      scrollDirection: Axis.horizontal,
      child: SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 4.0),
          child: DataTable(
            columnSpacing: 8.0,
            columns: [
              DataColumn(
                label: Text('Item'),
                numeric: true,
                tooltip: 'Item Name',
              ),
              DataColumn(
                label: Text('Price'),
                numeric: true,
                tooltip: 'Rate of Item',
              ),
              DataColumn(
                label: Text('Item2'),
                numeric: true,
                tooltip: 'Item Name',
              ),
              DataColumn(
                label: Text('Item3'),
                numeric: true,
                tooltip: 'Item Name',
              ),
              DataColumn(
                label: Text('Item4'),
                numeric: true,
                tooltip: 'Item Name',
              ),
              DataColumn(
                label: Text('Item5'),
                numeric: true,
                tooltip: 'Item Name',
              ),
              DataColumn(
                label: Text('Item6'),
                numeric: true,
                tooltip: 'Item Name',
              ),
              DataColumn(
                label: Text('Item7'),
                numeric: true,
                tooltip: 'Item Name',
              ),
              DataColumn(
                label: Text('Item8'),
                numeric: true,
                tooltip: 'Item Name',
              ),
              DataColumn(
                label: Text('Item9'),
                numeric: true,
                tooltip: 'Item Name',
              ),
              DataColumn(
                label: Text('Item10'),
                numeric: true,
                tooltip: 'Item Name',
              ),
              DataColumn(
                label: Text('Item11'),
                numeric: true,
                tooltip: 'Item Name',
              ),
            ].map((DataColumn column) {
              return DataColumn(
                label: column.label,
                numeric: column.numeric,
                tooltip: column.tooltip,
                onSort: column.onSort,
              );
            }).toList(),
            rows: [
              DataRow(cells: [
                DataCell(Text('Iron')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
              ]),
              DataRow(cells: [
                DataCell(Text('Gold')),
                DataCell(Text('750')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
              ]),
              DataRow(cells: [
                DataCell(Text('Gold')),
                DataCell(Text('750')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
              ]),
              DataRow(cells: [
                DataCell(Text('Gold')),
                DataCell(Text('750')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
              ]),
              DataRow(cells: [
                DataCell(Text('Gold')),
                DataCell(Text('750')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
              ]),
              DataRow(cells: [
                DataCell(Text('Gold')),
                DataCell(Text('750')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
              ]),
              DataRow(cells: [
                DataCell(Text('Gold')),
                DataCell(Text('750')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
              ]),
              DataRow(cells: [
                DataCell(Text('Gold')),
                DataCell(Text('750')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
              ]),
              DataRow(cells: [
                DataCell(Text('Gold')),
                DataCell(Text('750')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
              ]),
              DataRow(cells: [
                DataCell(Text('Gold')),
                DataCell(Text('750')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
              ]),
              DataRow(cells: [
                DataCell(Text('Gold')),
                DataCell(Text('750')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
              ]),
              DataRow(cells: [
                DataCell(Text('Gold')),
                DataCell(Text('750')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
              ]),
              DataRow(cells: [
                DataCell(Text('Gold')),
                DataCell(Text('750')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
              ]),
              DataRow(cells: [
                DataCell(Text('Gold')),
                DataCell(Text('750')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
              ]),
              DataRow(cells: [
                DataCell(Text('Gold')),
                DataCell(Text('750')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
              ]),
              DataRow(cells: [
                DataCell(Text('Gold')),
                DataCell(Text('750')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
              ]),
              DataRow(cells: [
                DataCell(Text('Gold')),
                DataCell(Text('750')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
              ]),
              DataRow(cells: [
                DataCell(Text('Gold')),
                DataCell(Text('750')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
              ]),
              DataRow(cells: [
                DataCell(Text('Gold')),
                DataCell(Text('750')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
              ]),
              DataRow(cells: [
                DataCell(Text('Gold')),
                DataCell(Text('750')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
              ]),
              DataRow(cells: [
                DataCell(Text('Gold')),
                DataCell(Text('750')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
              ]),
              DataRow(cells: [
                DataCell(Text('Gold')),
                DataCell(Text('750')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
              ]),
              DataRow(cells: [
                DataCell(Text('Gold')),
                DataCell(Text('750')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
              ]),
              DataRow(cells: [
                DataCell(Text('Gold')),
                DataCell(Text('750')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
                DataCell(Text('50')),
              ]),
              // Add more DataRow widgets for additional items
            ],
          ),
        ),
      ),
    );
  }
}

class DealersListPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      scrollDirection: Axis.horizontal,
      child: SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 4.0),
          child: DataTable(
            columnSpacing: 8.0, // Add spacing between columns
            columns: [
              DataColumn(
                label: Text('Srno'),
                numeric: true,
                tooltip: 'Serial Number',
              ),
              DataColumn(
                label: Text('ID'),
                tooltip: 'Identification Number',
              ),
              DataColumn(
                label: Text('Name'),
                tooltip: 'Name of the Dealer',
              ),
              DataColumn(
                label: Text('Rating'),
                numeric: true,
                tooltip: 'Rating of the Dealer',
              ),
              DataColumn(
                label: Text('Location'),
                tooltip: 'Location of the Dealer',
              ),
              DataColumn(
                label: Text('Location2'),
                tooltip: 'Location of the Dealer',
              ),
              DataColumn(
                label: Text('Location3'),
                tooltip: 'Location of the Dealer',
              ),
            ].map((DataColumn column) {
              return DataColumn(
                label: column.label,
                numeric: column.numeric,
                tooltip: column.tooltip,
                onSort: column.onSort,
              );
            }).toList(),
            rows: [
              DataRow(cells: [
                DataCell(Text('1')),
                DataCell(Text('2180')),
                DataCell(Text('Anmol')),
                DataCell(Text('6.9')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
              ]),

              DataRow(cells: [
                DataCell(Text('1')),
                DataCell(Text('2180')),
                DataCell(Text('Anmol')),
                DataCell(Text('6.9')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
              ]),
              DataRow(cells: [
                DataCell(Text('1')),
                DataCell(Text('2180')),
                DataCell(Text('Anmol')),
                DataCell(Text('6.9')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
              ]),
              DataRow(cells: [
                DataCell(Text('1')),
                DataCell(Text('2180')),
                DataCell(Text('Anmol')),
                DataCell(Text('6.9')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
              ]),
              DataRow(cells: [
                DataCell(Text('1')),
                DataCell(Text('2180')),
                DataCell(Text('Anmol')),
                DataCell(Text('6.9')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
              ]),
              DataRow(cells: [
                DataCell(Text('1')),
                DataCell(Text('2180')),
                DataCell(Text('Anmol')),
                DataCell(Text('6.9')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
              ]),
              DataRow(cells: [
                DataCell(Text('1')),
                DataCell(Text('2180')),
                DataCell(Text('Anmol')),
                DataCell(Text('6.9')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
              ]),
              DataRow(cells: [
                DataCell(Text('1')),
                DataCell(Text('2180')),
                DataCell(Text('Anmol')),
                DataCell(Text('6.9')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
              ]),
              DataRow(cells: [
                DataCell(Text('1')),
                DataCell(Text('2180')),
                DataCell(Text('Anmol')),
                DataCell(Text('6.9')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
              ]),
              DataRow(cells: [
                DataCell(Text('1')),
                DataCell(Text('2180')),
                DataCell(Text('Anmol')),
                DataCell(Text('6.9')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
              ]),
              DataRow(cells: [
                DataCell(Text('1')),
                DataCell(Text('2180')),
                DataCell(Text('Anmol')),
                DataCell(Text('6.9')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
              ]),
              DataRow(cells: [
                DataCell(Text('1')),
                DataCell(Text('2180')),
                DataCell(Text('Anmol')),
                DataCell(Text('6.9')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
              ]),
              DataRow(cells: [
                DataCell(Text('1')),
                DataCell(Text('2180')),
                DataCell(Text('Anmol')),
                DataCell(Text('6.9')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
              ]),
              DataRow(cells: [
                DataCell(Text('1')),
                DataCell(Text('2180')),
                DataCell(Text('Anmol')),
                DataCell(Text('6.9')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
              ]),
              DataRow(cells: [
                DataCell(Text('1')),
                DataCell(Text('2180')),
                DataCell(Text('Anmol')),
                DataCell(Text('6.9')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
              ]),
              DataRow(cells: [
                DataCell(Text('1')),
                DataCell(Text('2180')),
                DataCell(Text('Anmol')),
                DataCell(Text('6.9')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
              ]),
              DataRow(cells: [
                DataCell(Text('1')),
                DataCell(Text('2180')),
                DataCell(Text('Anmol')),
                DataCell(Text('6.9')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
              ]),
              DataRow(cells: [
                DataCell(Text('1')),
                DataCell(Text('2180')),
                DataCell(Text('Anmol')),
                DataCell(Text('6.9')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
              ]),
              DataRow(cells: [
                DataCell(Text('1')),
                DataCell(Text('2180')),
                DataCell(Text('Anmol')),
                DataCell(Text('6.9')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
              ]),
              DataRow(cells: [
                DataCell(Text('1')),
                DataCell(Text('2180')),
                DataCell(Text('Anmol')),
                DataCell(Text('6.9')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
              ]),
              DataRow(cells: [
                DataCell(Text('1')),
                DataCell(Text('2180')),
                DataCell(Text('Anmol')),
                DataCell(Text('6.9')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
                DataCell(Text('Karnal')),
              ]),
              // Add more DataRow widgets for additional dealers
            ],
          ),
        ),
      ),
    );
  }
}
