Map<String, List<String>> generateCitiesByState() {
  return {
    'Andhra Pradesh': [
      'Visakhapatnam',
      'Vijayawada',
      'Guntur',
      'Nellore',
      'Kurnool',
      'Rajahmundry',
      'Tirupati',
      'Kakinada',
      'Anantapur',
      'Vizianagaram',
      'Eluru',
      'Ongole'
    ],
    'Arunachal Pradesh': [
      'Itanagar',
      'Naharlagun',
      'Tawang',
      'Pasighat',
      'Bomdila',
      'Along',
      'Tezu',
      'Roing',
      'Ziro',
      'Daporijo',
      'Anini',
      'Khonsa'
    ],
    'Assam': [
      'Guwahati',
      'Silchar',
      'Dibrugarh',
      'Jorhat',
      'Nagaon',
      'Tinsukia',
      'Tezpur',
      'Sivasagar',
      'Bongaigaon',
      'Diphu',
      'North Lakhimpur',
      'Karimganj'
    ],
    'Bihar': [
      'Patna',
      'Gaya',
      'Bhagalpur',
      'Muzaffarpur',
      'Purnia',
      'Darbhanga',
      'Bihar Sharif',
      'Arrah',
      'Begusarai',
      'Katihar',
      'Munger',
      'Chhapra'
    ],
    'Chhattisgarh': [
      'Raipur',
      'Bhilai',
      'Bilaspur',
      'Korba',
      'Rajnandgaon',
      'Raigarh',
      'Jagdalpur',
      'Ambikapur',
      'Dhamtari',
      'Durg',
      'Janjgir',
      'Mahasamund'
    ],
    'Goa': [
      'Panaji',
      'Margao',
      'Vasco da Gama',
      'Mapusa',
      'Ponda',
      'Bicholim',
      'Curchorem',
      'Sanquelim',
      'Valpoi',
      'Cuncolim',
      'Porvorim',
      'Calangute'
    ],
    'Gujarat': [
      'Ahmedabad',
      'Surat',
      'Vadodara',
      'Rajkot',
      'Bhavnagar',
      'Jamnagar',
      'Junagadh',
      'Gandhinagar',
      'Anand',
      'Nadiad',
      'Morbi',
      'Surendranagar'
    ],
    'Haryana': [
      'Faridabad',
      'Gurgaon',
      'Panipat',
      'Ambala',
      'Yamunanagar',
      'Rohtak',
      'Hisar',
      'Karnal',
      'Sonipat',
      'Panchkula',
      'Bhiwani',
      'Sirsa'
    ],
    'Himachal Pradesh': [
      'Shimla',
      'Solan',
      'Dharamshala',
      'Mandi',
      'Palampur',
      'Kullu',
      'Chamba',
      'Una',
      'Hamirpur',
      'Nahan',
      'Bilaspur',
      'Dalhousie'
    ],
    'Jharkhand': [
      'Ranchi',
      'Jamshedpur',
      'Dhanbad',
      'Bokaro Steel City',
      'Deoghar',
      'Hazaribagh',
      'Giridih',
      'Ramgarh',
      'Medininagar',
      'Chirkunda',
      'Phusro',
      'Saunda'
    ],
    'Karnataka': [
      'Bangalore',
      'Mysore',
      'Hubli',
      'Mangalore',
      'Belgaum',
      'Gulbarga',
      'Davanagere',
      'Bellary',
      'Bijapur',
      'Shimoga',
      'Tumkur',
      'Raichur'
    ],
    'Kerala': [
      'Thiruvananthapuram',
      'Kochi',
      'Kozhikode',
      'Kollam',
      'Thrissur',
      'Malappuram',
      'Palakkad',
      'Alappuzha',
      'Kannur',
      'Kottayam',
      'Manjeri',
      'Kasaragod'
    ],
    'Madhya Pradesh': [
      'Indore',
      'Bhopal',
      'Jabalpur',
      'Gwalior',
      'Ujjain',
      'Sagar',
      'Dewas',
      'Satna',
      'Ratlam',
      'Rewa',
      'Chhindwara',
      'Shivpuri'
    ],
    'Maharashtra': [
      'Mumbai',
      'Pune',
      'Nagpur',
      'Thane',
      'Nashik',
      'Kalyan-Dombivali',
      'Vasai-Virar',
      'Aurangabad',
      'Navi Mumbai',
      'Solapur',
      'Bhiwandi',
      'Amravati'
    ],
    'Manipur': [
      'Imphal',
      'Thoubal',
      'Lilong',
      'Bishnupur',
      'Kakching',
      'Mayang Imphal',
      'Nambol',
      'Lamai',
      'Sugnu',
      'Wangoi',
      'Sikhong Sekmai'
    ],
    'Meghalaya': [
      'Shillong',
      'Tura',
      'Nongstoin',
      'Williamnagar',
      'Nongpoh',
      'Jowai',
      'Baghmara',
      'Resubelpara',
      'Amlarem',
      'Mairang',
      'Cherrapunji'
    ],
    'Mizoram': [
      'Aizawl',
      'Lunglei',
      'Saiha',
      'Champhai',
      'Serchhip',
      'Kolasib',
      'Lawngtlai',
      'Mamit',
      'Khawhai',
      'Hnahthial',
      'Vairengte'
    ],
    'Nagaland': [
      'Kohima',
      'Dimapur',
      'Mokokchung',
      'Tuensang',
      'Wokha',
      'Zunheboto',
      'Phek',
      'Mon',
      'Chumukedima',
      'Medziphema',
      'Kiphire'
    ],
    'Odisha': [
      'Bhubaneswar',
      'Cuttack',
      'Rourkela',
      'Brahmapur',
      'Sambalpur',
      'Puri',
      'Balasore',
      'Bhadrak',
      'Baripada',
      'Jharsuguda',
      'Jeypore',
      'Bargarh'
    ],
    'Punjab': [
      'Ludhiana',
      'Amritsar',
      'Jalandhar',
      'Patiala',
      'Bathinda',
      'Hoshiarpur',
      'Mohali',
      'Batala',
      'Pathankot',
      'Moga',
      'Firozpur',
      'Kapurthala'
    ],
    'Rajasthan': [
      'Jaipur',
      'Jodhpur',
      'Kota',
      'Bikaner',
      'Ajmer',
      'Udaipur',
      'Bhilwara',
      'Alwar',
      'Bharatpur',
      'Sri Ganganagar',
      'Pali',
      'Sikar'
    ],
    'Sikkim': [
      'Gangtok',
      'Namchi',
      'Gyalshing',
      'Mangan',
      'Singtam',
      'Rangpo',
      'Jorethang',
      'Ravangla',
      'Naya Bazar',
      'Soreng',
      'Melli',
      'Rhenock'
    ],
    'Tamil Nadu': [
      'Chennai',
      'Coimbatore',
      'Madurai',
      'Tiruchirappalli',
      'Salem',
      'Tiruppur',
      'Erode',
      'Vellore',
      'Thoothukudi',
      'Tirunelveli',
      'Nagercoil',
      'Thanjavur'
    ],
    'Telangana': [
      'Hyderabad',
      'Warangal',
      'Nizamabad',
      'Khammam',
      'Karimnagar',
      'Ramagundam',
      'Mahbubnagar',
      'Nalgonda',
      'Adilabad',
      'Suryapet',
      'Miryalaguda',
      'Jagtial'
    ],
    'Tripura': [
      'Agartala',
      'Dharmanagar',
      'Udaipur',
      'Belonia',
      'Kailasahar',
      'Ambassa',
      'Santirbazar',
      'Khowai',
      'Kamalpur',
      'Sonamura',
      'Sabroom',
      'Bishramganj'
    ],
    'Uttar Pradesh': [
      'Lucknow',
      'Kanpur',
      'Ghaziabad',
      'Agra',
      'Varanasi',
      'Meerut',
      'Allahabad',
      'Bareilly',
      'Aligarh',
      'Moradabad',
      'Saharanpur',
      'Gorakhpur'
    ],
    'Uttarakhand': [
      'Dehradun',
      'Haridwar',
      'Roorkee',
      'Haldwani',
      'Rudrapur',
      'Kashipur',
      'Rishikesh',
      'Kotdwara',
      'Ramnagar',
      'Manglaur',
      'Jaspur',
      'Sitarganj'
    ],
    'West Bengal': [
      'Kolkata',
      'Asansol',
      'Siliguri',
      'Durgapur',
      'Bardhaman',
      'Malda',
      'Baharampur',
      'Habra',
      'Kharagpur',
      'Shantipur',
      'Dankuni',
      'Dhulian'
    ],
    'Andaman and Nicobar Islands': [
      'Port Blair',
      'South Andaman',
      'Bombooflat',
      'Mayabunder',
      'Rangat',
      'Diglipur',
      'Port Blair H.O',
      'Havelock Island',
      'Garacharma',
      'Prothrapur',
      'Ferrargunj',
      'Bambooflat'
    ],
    'Chandigarh': [
      'Chandigarh',
      'Panchkula',
      'Mohali',
      'Zirakpur',
      'Kharar',
      'Dera Bassi',
      'Baddi',
      'Naya Gaon',
      'Rupnagar',
      'Kurali',
      'Bilaspur',
      'Pinjore'
    ],
    'Dadra and Nagar Haveli and Daman and Diu': [
      'Silvassa',
      'Daman',
      'Diu',
      'Dadra',
      'Naroli',
      'Vapi',
      'Amli',
      'Rakholi',
      'Kanadi',
      'Bhimpore',
      'Dadra and Nagar Haveli',
      'Kachigam'
    ],
    'Delhi': [
      'New Delhi',
      'Delhi',
      'Noida',
      'Gurgaon',
      'Faridabad',
      'Ghaziabad',
      'Greater Noida',
      'Bahadurgarh',
      'Sonepat',
      'Panipat',
      'Meerut',
      'Rohtak'
    ],
    'Lakshadweep': [
      'Kavaratti',
      'Agatti Island',
      'Andrott',
      'Minicoy',
      'Amini',
      'Kadmat',
      'Kalpeni',
      'Chetlat',
      'Bitra',
      'Kiltan',
      'Bangaram'
    ],
    'Puducherry': [
      'Puducherry',
      'Karaikal',
      'Mahe',
      'Yanam',
      'Ozhukarai',
      'Villianur',
      'Ariankuppam',
      'Manavely',
      'Nellithope',
      'Bahour',
      'Lawspet',
      'Muthialpet'
    ]
  };
}
